import { getImageUrl } from "../../utils";

export const booksData = [
    { 
        id: 1, 
        title: 'The Great Gatsby', 
        author: 'F. Scott Fitzgerald', 
        imageUrl: getImageUrl("books/tgg.png"), 
        description: 'A novel about the American dream and the Roaring Twenties.',
    },
    { 
        id: 2, 
        title: '1984', 
        author: 'George Orwell', 
        imageUrl: getImageUrl("books/1984.png"), 
        description: 'A dystopian novel about totalitarianism and surveillance.',
    },
    { 
        id: 3, 
        title: 'To Kill a Mockingbird', 
        author: 'Harper Lee', 
        imageUrl: getImageUrl("books/tkam.png"), 
        description: 'A story of racial injustice in the deep South during the 1930s.',
    },
    { 
        id: 4, 
        title: 'Pride and Prejudice', 
        author: 'Jane Austen', 
        imageUrl: getImageUrl("books/pp.png"), 
        description: 'A romantic novel that deals with issues of marriage, money, and love.',
    },
    { 
        id: 5, 
        title: 'Moby-Dick', 
        author: 'Herman Melville', 
        imageUrl: getImageUrl("books/md.png"), 
        description: 'The adventures of Captain Ahab and his obsessive quest to hunt the white whale.',
    },
    // Additional 70 books
    { id: 6, title: 'War and Peace', author: 'Leo Tolstoy', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A historical novel that intertwines the lives of several characters during the Napoleonic Wars.' },
    { id: 7, title: 'The Catcher in the Rye', author: 'J.D. Salinger', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about teenage angst and alienation.' },
    { id: 8, title: 'The Odyssey', author: 'Homer', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'An epic poem that follows the adventures of Odysseus as he returns home from the Trojan War.' },
    { id: 9, title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A philosophical novel exploring morality, free will, and faith.' },
    { id: 10, title: 'Brave New World', author: 'Aldous Huxley', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A dystopian novel about a technologically advanced society.' },
    { id: 11, title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about vanity and moral corruption.' },
    { id: 12, title: 'The Grapes of Wrath', author: 'John Steinbeck', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about the struggles of a family during the Great Depression.' },
    { id: 13, title: 'Jane Eyre', author: 'Charlotte Brontë', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel that explores themes of love, morality, and social criticism.' },
    { id: 14, title: 'Wuthering Heights', author: 'Emily Brontë', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A tale of passion and revenge on the Yorkshire moors.' },
    { id: 15, title: 'Fahrenheit 451', author: 'Ray Bradbury', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A dystopian novel about a future where books are banned.' },
    { id: 16, title: 'The Hobbit', author: 'J.R.R. Tolkien', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A fantasy novel about the adventures of Bilbo Baggins.' },
    { id: 17, title: 'The Lord of the Rings: The Fellowship of the Ring', author: 'J.R.R. Tolkien', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'The first part of the epic fantasy trilogy.' },
    { id: 18, title: 'The Lord of the Rings: The Two Towers', author: 'J.R.R. Tolkien', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'The second part of the epic fantasy trilogy.' },
    { id: 19, title: 'The Lord of the Rings: The Return of the King', author: 'J.R.R. Tolkien', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'The concluding part of the epic fantasy trilogy.' },
    { id: 20, title: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', author: 'C.S. Lewis', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A fantasy novel about children who discover a magical land.' },
    { id: 21, title: 'The Alchemist', author: 'Paulo Coelho', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a shepherd’s journey to find his personal legend.' },
    { id: 22, title: 'The Fault in Our Stars', author: 'John Green', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A love story between two teenagers with cancer.' },
    { id: 23, title: 'The Kite Runner', author: 'Khaled Hosseini', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story of friendship and redemption set in Afghanistan.' },
    { id: 24, title: 'The Book Thief', author: 'Markus Zusak', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel narrated by Death, set in Nazi Germany.' },
    { id: 25, title: 'Life of Pi', author: 'Yann Martel', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story of survival and spirituality on a lifeboat.' },
    { id: 26, title: 'The Road', author: 'Cormac McCarthy', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A post-apocalyptic novel about a father and son’s journey.' },
    { id: 27, title: 'The Handmaid’s Tale', author: 'Margaret Atwood', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A dystopian novel about a totalitarian society.' },
    { id: 28, title: 'The Bell Jar', author: 'Sylvia Plath', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A semi-autobiographical novel about mental illness.' },
    { id: 29, title: 'The Secret Garden', author: 'Frances Hodgson Burnett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A children’s novel about a hidden garden and personal growth.' },
    { id: 30, title: 'The Little Prince', author: 'Antoine de Saint-Exupéry', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A philosophical tale about a young prince from another planet.' },
    { id: 31, title: 'The Great Expectations', author: 'Charles Dickens', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A coming-of-age story about an orphan named Pip.' },
    { id: 32, title: 'The Old Man and the Sea', author: 'Ernest Hemingway', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A short novel about an old fisherman’s struggle with a marlin.' },
    { id: 33, title: 'The Sun Also Rises', author: 'Ernest Hemingway', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a group of American and British expatriates in Paris.' },
    { id: 34, title: 'The Sound and the Fury', author: 'William Faulkner', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel that tells the story of the Compson family.' },
    { id: 35, title: 'The Stranger', author: 'Albert Camus', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A philosophical novel about absurdism and existentialism.' },
    { id: 36, title: 'The Metamorphosis', author: 'Franz Kafka', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novella about a man who transforms into a giant insect.' },
    { id: 37, title: 'The Hitchhiker’s Guide to the Galaxy', author: 'Douglas Adams', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A comedic science fiction series that follows the adventures of Arthur Dent.' },
    { id: 38, title: 'The Color Purple', author: 'Alice Walker', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the struggles of African American women in the early 20th century.' },
    { id: 39, title: 'The Road Less Traveled', author: 'M. Scott Peck', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A guide to personal growth and spiritual development.' },
    { id: 40, title: 'The Art of War', author: 'Sun Tzu', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'An ancient Chinese military treatise on strategy and tactics.' },
    { id: 41, title: 'The Diary of a Young Girl', author: 'Anne Frank', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'The diary of a Jewish girl hiding from the Nazis during World War II.' },
    { id: 42, title: 'The Catch-22', author: 'Joseph Heller', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A satirical novel about the absurdities of war.' },
    { id: 43, title: 'The Perks of Being a Wallflower', author: 'Stephen Chbosky', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A coming-of-age novel told through letters from a high school student.' },
    { id: 44, title: 'The Giver', author: 'Lois Lowry', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A dystopian novel about a society that has eliminated pain and suffering.' },
    { id: 45, title: 'The Glass Castle', author: 'Jeannette Walls', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A memoir about the author’s unconventional and often difficult childhood.' },
    { id: 46, title: 'The Immortal Life of Henrietta Lacks', author: 'Rebecca Skloot', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A nonfiction book about the woman whose cells were used for medical research.' },
    { id: 47, title: 'The Night Circus', author: 'Erin Morgenstern', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A fantasy novel about a magical competition between two young illusionists.' },
    { id: 48, title: 'The Time Traveler’s Wife', author: 'Audrey Niffenegger', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A love story about a man with a genetic disorder that causes him to time travel.' },
    { id: 49, title: 'The Fault in Our Stars', author: 'John Green', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A poignant love story between two teenagers with cancer.' },
    { id: 50, title: 'The Lovely Bones', author: 'Alice Sebold', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a young girl who watches from her personal heaven after being murdered.' },
    { id: 51, title: 'The Secret Life of Bees', author: 'Sue Monk Kidd', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A coming-of-age story set in South Carolina during the civil rights movement.' },
    { id: 52, title: 'The Help', author: 'Kathryn Stockett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about African American maids working in white households in the 1960s.' },
    { id: 53, title: 'The Girl on the Train', author: 'Paula Hawkins', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a woman who becomes entangled in a missing person investigation.' },
    { id: 54, title: 'Big Little Lies', author: 'Liane Moriarty', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the secrets and lies of three women in a suburban community.' },
    { id: 55, title: 'The Silent Patient', author: 'Alex Michaelides', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a woman who shoots her husband and then stops speaking.' },
    { id: 56, title: 'Where the Crawdads Sing', author: 'Delia Owens', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A coming-of-age story set in the marshes of North Carolina.' },
    { id: 57, title: 'Anxious People', author: 'Fredrik Backman', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A poignant story about a failed bank robbery and the people involved.' },
    { id: 58, title: 'The Vanishing Half', author: 'Brit Bennett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A multi-generational story about two twin sisters who choose to live in two very different worlds.' },
    { id: 59, title: 'The Midnight Library', author: 'Matt Haig', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a library that allows you to explore different versions of your life.' },
    { id: 60, title: 'Circe', author: 'Madeline Miller', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A retelling of the story of Circe, the witch from Greek mythology.' },
    { id: 61, title: 'The Seven Husbands of Evelyn Hugo', author: 'Taylor Jenkins Reid', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A fictional biography of a reclusive Hollywood star.' },
    { id: 62, title: 'Daisy Jones & The Six', author: 'Taylor Jenkins Reid', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A fictional oral history of a rock band in the 1970s.' },
    { id: 63, title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about a young woman who makes a deal to live forever but is forgotten by everyone she meets.' },
    { id: 64, title: 'The Song of Achilles', author: 'Madeline Miller', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A retelling of the story of Achilles and Patroclus.' },
    { id: 65, title: 'The Nightingale', author: 'Kristin Hannah', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A historical novel about two sisters in France during World War II.' },
    { id: 66, title: 'The Tattooist of Auschwitz', author: 'Heather Morris', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel based on the true story of a Holocaust survivor.' },
    { id: 67, title: 'The Book of Longings', author: 'Sue Monk Kidd', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the imagined life of Jesus’ wife.' },
    { id: 68, title: 'The Overstory', author: 'Richard Powers', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A Pulitzer Prize-winning novel about the interconnectedness of human lives and trees.' },
    { id: 69, title: 'Normal People', author: 'Sally Rooney', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the complex relationship between two Irish teenagers.' },
    { id: 70, title: 'The Light We Lost', author: 'Jill Santopolo', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A love story that spans years and continents.' },
    { id: 71, title: 'Eleanor Oliphant Is Completely Fine', author: 'Gail Honeyman', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a socially awkward woman and her journey to find connection.' },
    { id: 72, title: 'The Guest List', author: 'Lucy Foley', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A thriller set during a wedding on a remote Irish island.' },
    { id: 73, title: 'The Chain', author: 'Adrian McKinty', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a kidnapping chain.' },
    { id: 74, title: 'The Woman in the Window', author: 'A.J. Finn', imageUrl: getImageUrl("books/book-cover-placeholder .png"), description: 'A psychological thriller about an agoraphobic woman who believes she has witnessed a crime.' },
    { id: 75, title: 'The Silent Patient', author: 'Alex Michaelides', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a woman who shoots her husband and then stops speaking.' },
    { id: 76, title: 'The Guest Book', author: 'Sarah Blake', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A multi-generational saga about a wealthy family and their secrets.' },
    { id: 77, title: 'The Water Dancer', author: 'Ta-Nehisi Coates', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about slavery and the power of memory.' },
    { id: 78, title: 'The Dutch House', author: 'Ann Patchett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about a brother and sister and their childhood home.' },
    { id: 79, title: 'The Vanishing Half', author: 'Brit Bennett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A multi-generational story about two twin sisters who choose to live in two very different worlds.' },
    { id: 80, title: 'The Midnight Library', author: 'Matt Haig', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a library that allows you to explore different versions of your life.' },
    { id: 81, title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about a young woman who makes a deal to live forever but is forgotten by everyone she meets.' },
    { id: 82, title: 'The Song of Achilles', author: 'Madeline Miller', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A retelling of the story of Achilles and Patroclus.' },
    { id: 83, title: 'The Nightingale', author: 'Kristin Hannah', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A historical novel about two sisters in France during World War II.' },
    { id: 84, title: 'The Tattooist of Auschwitz', author: 'Heather Morris', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel based on the true story of a Holocaust survivor.' },
    { id: 85, title: 'The Book of Longings', author: 'Sue Monk Kidd', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the imagined life of Jesus’ wife.' },
    { id: 86, title: 'The Overstory', author: 'Richard Powers', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A Pulitzer Prize-winning novel about the interconnectedness of human lives and trees.' },
    { id: 87, title: 'Normal People', author: 'Sally Rooney', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about the complex relationship between two Irish teenagers.' },
    { id: 88, title: 'The Light We Lost', author: 'Jill Santopolo', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A love story that spans years and continents.' },
    { id: 89, title: 'Eleanor Oliphant Is Completely Fine', author: 'Gail Honeyman', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a socially awkward woman and her journey to find connection.' },
    { id: 90, title: 'The Guest List', author: 'Lucy Foley', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A thriller set during a wedding on a remote Irish island.' },
    { id: 91, title: 'The Chain', author: 'Adrian McKinty', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a kidnapping chain.' },
    { id: 92, title: 'The Woman in the Window', author: 'A.J. Finn', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about an agoraphobic woman who believes she has witnessed a crime.' },
    { id: 93, title: 'The Silent Patient', author: 'Alex Michaelides', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A psychological thriller about a woman who shoots her husband and then stops speaking.' },
    { id: 94, title: 'The Guest Book', author: 'Sarah Blake', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A multi-generational saga about a wealthy family and their secrets.' },
    { id: 95, title: 'The Water Dancer', author: 'Ta-Nehisi Coates', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about slavery and the power of memory.' },
    { id: 96, title: 'The Dutch House', author: 'Ann Patchett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about a brother and sister and their childhood home.' },
    { id: 97, title: 'The Vanishing Half', author: 'Brit Bennett', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A multi-generational story about two twin sisters who choose to live in two very different worlds.' },
    { id: 98, title: 'The Midnight Library', author: 'Matt Haig', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A novel about a library that allows you to explore different versions of your life.' },
    { id: 99, title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A story about a young woman who makes a deal to live forever but is forgotten by everyone she meets.' },
    { id: 100, title: 'The Song of Achilles', author: 'Madeline Miller', imageUrl: getImageUrl("books/book-cover-placeholder.png"), description: 'A retelling of the story of Achilles and Patroclus.' },
];